export const RECEIVE_STUDENT = 'RECEIVE_STUDENT';
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS';

export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES';
export const RECEIVE_CAMPUS = 'RECEIVE_CAMPUS';
export const RECEIVE_CAMPUS_STUDENTS = 'RECEIVE_CAMPUS_STUDENTS'