export const RECEIVE_STUDENT = 'RECEIVE_STUDENT';
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'

export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES';
export const RECEIVE_CAMPUS = 'RECEIVE_CAMPUS';
export const RECEIVE_CAMPUS_STUDENTS = 'RECEIVE_CAMPUS_STUDENTS'